update scripts

diff --git a/scripts/openapi-update-version b/scripts/openapi-update-version
--- a/scripts/openapi-update-version
+++ b/scripts/openapi-update-version
@@ -47,7 +47,7 @@ esac
 
 # Add information about snapshot
 if $snapshot; then
-    branch="$($script_dir/branch-name)" || (>2& echo "can't determine new version" && exit 1)
+    branch="$(bash $script_dir/branch-name)" || (>2& echo "can't determine new version" && exit 1)
     time="$(date +"%d-%m-%H-%M")"
     new_version="${new_version}-SNAPSHOT-${branch}-${time}"
 fi
